# G1 Standing Training Config - FIXED VERSION
# Dựa trên dự án hoạt động tốt với PD Controller + Assist System

# Simulation parameters
simulation_dt: 0.002
control_decimation: 5  # 100 Hz control frequency

# PD Control gains - VỪA PHẢI để đứng thẳng
kps: [50, 40, 50, 80, 50, 25, 50, 40, 50, 80, 50, 25]
kds: [2, 2, 2, 3, 2, 1, 2, 2, 2, 3, 2, 1]

# Action scaling - NHỎ để đứng thẳng
action_scale: 0.001  # NHỎ để đứng thẳng

# Command (standing = no movement)
cmd_scale: [0.0, 0.0, 0.0]
cmd_init: [0.0, 0.0, 0.0]

# Default angles - TỐI ƯU cho standing
default_angles: [-0.12, 0.00, +0.08, +0.34, -0.16, +0.02, -0.12, 0.00, +0.08, +0.34, -0.16, +0.02]

# Observation scales
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05

# Action và observation dimensions
num_actions: 12
num_obs: 47

# Assist system - HỖ TRỢ đứng vững
assist:
  enable: true
  sec: 8.0
  residual_min: 0.15
  k_ankle_pitch: 0.18
  k_hip_pitch: 0.06
  k_vx_feed: 0.10
  k_vx_err: 0.30

# Governor system - KIỂM SOÁT tốc độ và góc
governor:
  vx_margin: 0.12
  speed_gain: 1.5
  pitch_rad: 0.35
  pitch_gain: 0.9

# Bias system - ĐIỀU CHỈNH ban đầu
bias:
  hip_deg: -3.0
  ankle_deg: +2.0
  gain: 0.18
  duration: 2.0

# Target parameters
target_height: 0.20  # RẤT THẤP để đứng vững
fall_height_threshold: 0.20
tilt_threshold: 0.3
